In [1]:
import numpy as np
import pandas as pd

Python program to add two Matrices

In [12]:
list = [1,3,5,6]
list_1 = [5,6,7,2]
m_1 = np.array([list,list_1])
print(m_1)

[[1 3 5 6]
 [5 6 7 2]]


In [13]:
list_2 = [8,9,5,8]
list_3 = [3,2,4,1]
m_2 = np.array([list_2,list_3])
print(m_2)

[[8 9 5 8]
 [3 2 4 1]]


In [11]:
c = m_1 + m_2
print(c)

[[ 9 12 10 14]
 [ 8  8 11  3]]


Python program to multiply two matrices

In [19]:
print('matrix 1 =' ,m_1)
print('matrix 2 = ',m_2)
matrix_mul = m_1 * m_2
print('multiplication of matrices =',matrix_mul)

matrix 1 = [[1 3 5 6]
 [5 6 7 2]]
matrix 2 =  [[8 9 5 8]
 [3 2 4 1]]
multiplication of matrices = [[ 8 27 25 48]
 [15 12 28  2]]


Python program for Matrix Product

In [50]:
np.prod(m_1)

37800

Adding and Subtracting Matrices in Python

In [51]:
sum = m_1 +m_2
print(sum)

[[ 9 12 10 14]
 [ 8  8 11  3]]


In [52]:
sub = m_1 - m_2
print(sub)

[[-7 -6  0 -2]
 [ 2  4  3  1]]


Transpose a matrix in Single line in Python

In [53]:
np.transpose(m_1)

array([[1, 5],
       [3, 6],
       [5, 7],
       [6, 2]])

Python | Matrix creation of n*n

In [4]:
np.random.rand(4,4)

array([[0.3842804 , 0.40405994, 0.84443898, 0.97968907],
       [0.46065485, 0.48460678, 0.25808241, 0.33989471],
       [0.52453713, 0.61651173, 0.1297885 , 0.94578507],
       [0.13615581, 0.50204488, 0.64498357, 0.21841522]])

Python | Get Kth Column of Matrix

In [8]:
a = np.random.rand(3,3)
print(a)

[[0.42992195 0.47735539 0.27652832]
 [0.54604168 0.84655475 0.3822883 ]
 [0.58952082 0.85275965 0.52394203]]


In [11]:
a[:,1]

array([0.47735539, 0.84655475, 0.85275965])

Python – Vertical Concatenation in Matrix

In [19]:
b = np.random.rand(3,2)
print(b)


[[0.16374265 0.30688363]
 [0.67330414 0.97601693]
 [0.79338603 0.19843279]]


In [20]:
c = np.random.rand(3,2)
print(c)

[[0.57500831 0.28353992]
 [0.46771005 0.6351683 ]
 [0.2487001  0.81743996]]


In [21]:
np.concatenate((b, c), axis=0)

array([[0.16374265, 0.30688363],
       [0.67330414, 0.97601693],
       [0.79338603, 0.19843279],
       [0.57500831, 0.28353992],
       [0.46771005, 0.6351683 ],
       [0.2487001 , 0.81743996]])

Python program to check if a string is palindrome or not

In [29]:
def palindrome(s): 
    
    for i in range(0,int(len(s)/2)):
        if s[i] == s[len(s)-i-1]:
            return True
    return False
s = 'wertrew'
ans = palindrome(s)
if ans:
    print('yes')
else:
    print('no')

yes


Python program to check whether the string is Symmetrical or Palindrome


In [28]:
def palindrome(s): 
    
    for i in range(0,int(len(s)/2)):
        if s[i] == s[len(s)-i-1]:
            return True
    return False
s = 'wertrew'
ans = palindrome(s)
if ans:
    print('yes, it is palindrome')
else:
    print('it is not palindrome')
    
def symmetrical(s): 
    
    for i in range(0,(int(len(s)/2)-1)):
        if s[i] == s[int((len(s)/2)+i)]:
            return True
    return False
s = 'wertrew'
ans = symmetrical(s)
if ans:
    print('yes it is symmetrical')
else:
    print('it is not symmetrical')

yes, it is palindrome
it is not symmetrical
